### ISSUE TITLE
User testing Project Link in site header stuff

### ISSUE THREAD

**Issue by jonadecker** [GSA-TTS/10x-website#179]
User test header link to GH Project Board with relevant audiences of the 10x website:

 - past, prospective, and current idea authors
 - other venture-space folks?
 - SMEs who may be validating outreach from project teams (inside gov only?) or just curious

**Tasks**
- [ ] create recruitment copy and share with @willcahoe 
- [ ] establish our design hypotheses
- [ ] mock up potential approaches
- [ ] iterate

**Comment by maomeara63** [comment]
Copy for @willcahoe to review and approve

[Outreach copy](https://docs.google.com/document/d/1neOKeofRZ0T-NeVWJQvGIZdmlASo4l4ALnUxJW87uPY/edit?usp=sharing)

**Comment by jonathanbobel** [comment]
![Image](https://github.com/GSA-TTS/10x-website/assets/1233986/6857765c-3e83-48da-8631-d1bb94be2c41)
![Image](https://github.com/GSA-TTS/10x-website/assets/1233986/a2a76078-86ce-4f5d-9a77-2f4e144d338f)
![Image](https://github.com/GSA-TTS/10x-website/assets/1233986/9c6b6622-40a3-464a-bb00-a4203352d1af)
![Image](https://github.com/GSA-TTS/10x-website/assets/1233986/bd578c92-22fc-4bf2-9133-b5c3c1baef80)
![Image](https://github.com/GSA-TTS/10x-website/assets/1233986/92c79119-ac0a-4a6d-bc40-b9dac6257c73)

**Comment by jonathanbobel** [comment]
![Image](https://github.com/GSA-TTS/10x-website/assets/1233986/33e06a36-baff-4b64-8136-f5cdb1ad1254)
![Image](https://github.com/GSA-TTS/10x-website/assets/1233986/a9915bf1-e8f9-40e8-b724-24f7766dcf4c)
![Image](https://github.com/GSA-TTS/10x-website/assets/1233986/de0f2517-0da3-4a8f-a992-eafb0f853aab)
![Image](https://github.com/GSA-TTS/10x-website/assets/1233986/ac360549-e899-45b7-bdc6-90ee891e60ee)
![Image](https://github.com/GSA-TTS/10x-website/assets/1233986/dbcecc21-4eb2-4a33-9ff2-de9a48b5a028)

**Comment by jonathanbobel** [comment]
**Updated designs after feedback:**

![Image](https://github.com/user-attachments/assets/04d37efa-1a6e-41e2-b85b-9dc0899477a6)

![Image](https://github.com/user-attachments/assets/1961feaa-4a46-405c-adfc-e6c971a7e332)

**Comment by jonathanbobel** [comment]
@marina-defrates Please take a look

**Comment by jonadecker** [comment]
Per @nicopapafil and @marina-defrates feedback, **Option 2** (stacked nav) is the direction we'll move forward with.
