### ISSUE TITLE
User Story: Project status link in site header

### ISSUE THREAD

**Issue by jonadecker** [GSA-TTS/10x-website#202]
### Story

As a previous or potential Idea Author, I want to be able to easily find a submitted idea so that I learn what ideas are in the 10x pipeline, an idea's current phase and status, and what ideas are moving forward or ending. 

I might want to be able to link to an idea if I'm the author (for a performance plan), or reach out to a team with subject matter expertise.

### DoD

1. Project status link is prominently located in 10x header (desktop and mobile)
2. Project status link purpose is clear from label
3. Project status link takes user to Github Project Board kanban

### Tasks

- [x] Spike on design options #179 
- [x] User testing of design options
- [x] Iteration on user feedback
- [x] Sharing of user research with website manager and comms team
- [x] Iteration on website manager/comms team feedback
- [x] Sharing of revised design options with 10x leadership
- [x] Decision on design direction #179 
- [x] Design updates in feature branch
- [ ] Cross browser and accessibility testing in feature branch
- [ ] Approved for production

**Comment by jonadecker** [comment]
Feature branch has been run through AMP (no errors/warnings/cautions) but voiceover and manual testing may provide some opportunities to improvements.

**Comment by natashapl** [comment]
Hi @iamjolly . Hope all is well. In this task, we've updated the main top navigation of the 10x website and added a "Project Status" link. When you have a moment, could you please perform some additional accessibility testing and let us know if we overlooked anything? Thanks so much!
