### ISSUE TITLE
User Story: Add program logos to Featured Products on 10x home page

### ISSUE THREAD

**Issue by jonadecker** [GSA-TTS/10x-website#203]
### DoD

1. Product  icon is displayed adjacent to Program name on Featured Product cards on 10x home page  (desktop and mobile)

### Tasks

- [x] Spike on design options #189 
- [ ] Sharing of design options with website manager and comms team
- [x] Iteration on website manager/comms team feedback
- [x] Sharing of revised design options with 10x leadership
- [x] Decision on design direction #189 
- [ ] Design updates in feature branch
- [ ] Cross browser and accessibility testing in feature branch
- [ ] Approved for production
