### ISSUE TITLE
Impact Reports

### ISSUE THREAD

**Issue by jonadecker** [GSA-TTS/10x-website#55]
**USER STORY**

As a federal employee or member of the media, I want to be able to find and read 10x's impact reports by year.

Informed by #102, #126, #103, #116   

- [X] Preliminary content for FY23 Impact Report
- [x] [Figma design for FY23 ](#103) (Jon)
- [x] Reuse content from the legacy website or rewrite to get previous FY Impact reports working on new site (Natasha)
- [ ] Code [Impact Reports landing design](#92)
- [ ] Approved design for FY23 Impact Report (Will)
- [ ] Approved content for FY23 Impact Report (Will)
- [ ] Final (proofread) content (Julia)
- [ ] Code [FY23 IR design](#103 ) (Natasha)
- [ ] FY22 and FY21 Impact Report designs (Natasha)

**ACCEPTANCE CRITERIA**

- [ ]  Design implemented as approved
- [ ]  Link to each impact report
- [ ]  Redirects updated
- [ ] Reindexation requested

**DEFINITION OF DONE**

- [ ] Acceptance criteria met
- [ ] Usability validated
- [ ] Design QA passed
- [ ] Accessibility tests passed
- [ ] KPIs identified
- [ ] Code refactored for clarity
- [ ] Dependency Rule followed
- [ ] Development debt eliminated
- [ ] Source code merged
- [ ] Code reviewed
- [ ] Build process updated
- [ ] Load/performance tests passed
- [ ] Documents are updated
